### ISSUE TITLE
Go mod cannot find module 

### ISSUE THREAD

**Issue by psiservices-scohen** [bxcodec/faker#51]
Since the 2.01 update, go modules cannot find the module

unknown import path "github.com/bxcodec/faker": cannot find module providing package github.com/bxcodec/faker

It did work with version v2.0.0

**Comment by bxcodec** [comment]
Thanks for the reports, will investigate this issue ASAP 🙏

**Comment by bxcodec** [comment]
Hi @psiservices-scohen,
It works well for me, I don't know why it's not working on you

**Comment by psiservices-scohen** [comment]
Hmm, really strange.  I cloned my project into a new folder ran the go mod init  command, then try and build - this is the output:

[org_onboarding]$ go build
go: finding github.com/ably/ably-go/ably latest
go: finding github.com/go-chi/chi/middleware latest
go: finding github.com/asaskevich/govalidator latest
go: finding gopkg.in/mgo.v2 latest
go: finding github.com/ugorji/go/codec latest
build org_onboarding: cannot find module for path github.com/bxcodec/faker

go.mod file is missing your package:
module org_onboarding

require (
	github.com/ably/ably-go v1.1.0
	github.com/asaskevich/govalidator v0.0.0-20180720115003-f9ffefc3facf
	github.com/go-chi/chi v4.0.1+incompatible
	github.com/imdario/mergo v0.3.7
	github.com/rs/cors v1.6.0
	github.com/ugorji/go/codec v0.0.0-20190128213124-ee1426cffec0 // indirect
	gopkg.in/mgo.v2 v2.0.0-20180705113604-9856a29383ce
)

But it does exist in the go.sum file:
github.com/ably/ably-go v1.1.0 h1:L3WA+AxO4sS82gMIGg2W5c49ORj0QHEqp4N+GWzirv8=
github.com/ably/ably-go v1.1.0/go.mod h1:YDhXHXz54Jv1ut4stKHPtLgF3Bi1KvqyKDY12MpYJLQ=
github.com/asaskevich/govalidator v0.0.0-20180720115003-f9ffefc3facf h1:eg0MeVzsP1G42dRafH3vf+al2vQIJU0YHX+1Tw87oco=
github.com/asaskevich/govalidator v0.0.0-20180720115003-f9ffefc3facf/go.mod h1:lB+ZfQJz7igIIfQNfa7Ml4HSf2uFQQRzpGGRXenZAgY=
github.com/bxcodec/faker v2.0.1+incompatible h1:P0KUpUw5w6WJXwrPfv35oc91i4d8nf40Nwln+M/+faA=
github.com/go-chi/chi v4.0.1+incompatible h1:RSRC5qmFPtO90t7pTL0DBMNpZFsb/sHF3RXVlDgFisA=
github.com/go-chi/chi v4.0.1+incompatible/go.mod h1:eB3wogJHnLi3x/kFX2A+IbTBlXxmMeXJVKy9tTv1XzQ=
github.com/imdario/mergo v0.3.7 h1:Y+UAYTZ7gDEuOfhxKWy+dvb5dRQ6rJjFSdX2HZY1/gI=
github.com/imdario/mergo v0.3.7/go.mod h1:2EnlNZ0deacrJVfApfmtdGgDfMuh/nq6Ok1EcJh5FfA=
github.com/rs/cors v1.6.0 h1:G9tHG9lebljV9mfp9SNPDL36nCDxmo3zTlAf1YgvzmI=
github.com/rs/cors v1.6.0/go.mod h1:gFx+x8UowdsKA9AchylcLynDq+nNFfI8FkUZdN/jGCU=
github.com/ugorji/go v1.1.2 h1:JON3E2/GPW2iDNGoSAusl1KDf5TRQ8k8q7Tp097pZGs=
github.com/ugorji/go v1.1.2/go.mod h1:hnLbHMwcvSihnDhEfx2/BzKp2xb0Y+ErdfYcrs9tkJQ=
github.com/ugorji/go/codec v0.0.0-20190128213124-ee1426cffec0 h1:Q3Bh5Dwzek5LreV9l86IftyLaexgU1mag9WNntbAW9c=
github.com/ugorji/go/codec v0.0.0-20190128213124-ee1426cffec0/go.mod h1:iT03XoTwV7xq/+UGwKO3UbC1nNNlopQiY61beSdrtOA=
gopkg.in/mgo.v2 v2.0.0-20180705113604-9856a29383ce h1:xcEWjVhvbDy+nHP67nPDDpbYrY+ILlfndk4bRioVHaU=
gopkg.in/mgo.v2 v2.0.0-20180705113604-9856a29383ce/go.mod h1:yeKp02qBN3iKW1OzL3MGk2IdtZzaj7SFntXj72NppTA=

**Comment by bxcodec** [comment]
That's weird, somehow I can't reproduce as you do.

What happens if you just `go get github.com/bxcodec/faker` again from scratch? Is it still raising the error?

**Comment by psiservices-scohen** [comment]
I'm going to blow away my project folder and recreate from backup - very strange that it's just this package.

**Comment by bxcodec** [comment]
Lol. Alright then, so I'll close this issue for a while. If anything comes up, just reopen this issue.
And also I'm planning to move this project to Go mod soon. Just in case if this happens because this project is not moved to Go module yet. But I'm still looking for the spare time to do this. :D

**Comment by psiservices-scohen** [comment]
Restore - works again, so who knows -   Thanks!
